---
title: "Hiato do Produto vs. Taxa de Desemprego"
author: 
date: "`r format(Sys.time(), '%d de %B, %Y')`"
abstract: "Fazemos uma comparação entre o hiato do produto e a taxa de desemprego dessazonalizada nesse comentário de conjuntura."
output: 
  pdf_document:
    toc: true
    number_sections: true
    includes:
      in_header: header.tex
geometry: margin=1in
fontfamily: mathpazo
fontsize: 11pt
bibliography: 'references.bib'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
def.chunk.hook  <- knitr::knit_hooks$get("chunk")
knitr::knit_hooks$set(chunk = function(x, options) {
  x <- def.chunk.hook(x, options)
  ifelse(options$size != "normalsize", paste0("\\", options$size,"\n\n", x, "\n\n \\normalsize"), x)
})

```

\newpage
# Pacotes

```{r, echo=T, eval=T, results='asis', fig.width=8, fig.height=4, fig.align='center', out.width="1\\linewidth", warning=FALSE, message=FALSE, size='small'}

library(forecast)
library(stargazer)
library(xtable)
library(ggplot2)
library(ggthemes)
library(sidrar)
library(scales)
library(gridExtra)
library(reshape2)
library(xts)
library(plyr)
library(readxl)
### Pacote Seasonal
library(seasonal)
Sys.setenv(X13_PATH = "C:/Séries Temporais/R/Pacotes/seas/x13ashtml")


```

# Coleta de dados da Pnad Contínua

```{r, echo=T, eval=T, results='asis', fig.width=8, fig.height=4, fig.align='center', out.width="1\\linewidth", warning=FALSE, message=FALSE, size='small'}

### Coletar dados no SIDRA IBGE
populacao = get_sidra(api='/t/6022/n1/all/v/606/p/all')$Valor
t1 = get_sidra(api='/t/6318/n1/all/v/1641/p/all/c629/all')
po = get_sidra(api='/t/6320/n1/all/v/4090/p/all/c11913/allxt')
po2 = get_sidra(api='/t/6323/n1/all/v/4090/p/all/c693/allxt')
renda = get_sidra(api='/t/6390/n1/all/v/5929,5933/p/all')
massa = get_sidra(api='/t/6392/n1/all/v/6288,6293/p/all')
### Obter séries individuais (pode ser mais rápido)
pia = t1$Valor[t1$`Condição em relação à força de trabalho e condição de ocupação (Código)`==32385]
pea = t1$Valor[t1$`Condição em relação à força de trabalho e condição de ocupação (Código)`==32386]
ocupada = t1$Valor[t1$`Condição em relação à força de trabalho e condição de ocupação (Código)`==32387]
desocupada = t1$Valor[t1$`Condição em relação à força de trabalho e condição de ocupação (Código)`==32446]
pnea = t1$Valor[t1$`Condição em relação à força de trabalho e condição de ocupação (Código)`==32447]
carteira = po$Valor[po$`Posição na ocupação e categoria do emprego no trabalho principal (Código)`=='31722']
scarteira = po$Valor[po$`Posição na ocupação e categoria do emprego no trabalho principal (Código)`=='31723']
domestico = po$Valor[po$`Posição na ocupação e categoria do emprego no trabalho principal (Código)`=='31724']
publico = po$Valor[po$`Posição na ocupação e categoria do emprego no trabalho principal (Código)`=='31727']
empregador = po$Valor[po$`Posição na ocupação e categoria do emprego no trabalho principal (Código)`=='96170']
cpropria = po$Valor[po$`Posição na ocupação e categoria do emprego no trabalho principal (Código)`=='96171']
tfa = po$Valor[po$`Posição na ocupação e categoria do emprego no trabalho principal (Código)`=='31731']
agro = po2$Valor[po2$`Grupamento de atividades no trabalho principal - PNADC (Código)`==33357]
ind = po2$Valor[po2$`Grupamento de atividades no trabalho principal - PNADC (Código)`==33358]
const = po2$Valor[po2$`Grupamento de atividades no trabalho principal - PNADC (Código)`==33360]
comercio = po2$Valor[po2$`Grupamento de atividades no trabalho principal - PNADC (Código)`==33361]
transporte = po2$Valor[po2$`Grupamento de atividades no trabalho principal - PNADC (Código)`==33362]
alojamento = po2$Valor[po2$`Grupamento de atividades no trabalho principal - PNADC (Código)`==33363]
informacao = po2$Valor[po2$`Grupamento de atividades no trabalho principal - PNADC (Código)`==33364]
admpub = po2$Valor[po2$`Grupamento de atividades no trabalho principal - PNADC (Código)`==39325]
outserv = po2$Valor[po2$`Grupamento de atividades no trabalho principal - PNADC (Código)`==33367]
servdom = po2$Valor[po2$`Grupamento de atividades no trabalho principal - PNADC (Código)`==33368]
rendanominal = renda$Valor[renda$`Variável (Código)`==5929]
rendareal = renda$Valor[renda$`Variável (Código)`==5933]
massanominal = massa$Valor[massa$`Variável (Código)`==6288]
massareal = massa$Valor[massa$`Variável (Código)`==6293]
### Consolidar
data = data.frame(populacao, pia, pea, ocupada, desocupada, 
                  pnea, carteira, 
                  scarteira, domestico, publico, empregador, 
                  cpropria, tfa, agro, ind, const, comercio,
                  transporte, alojamento, informacao, admpub,
                  outserv, servdom, rendanominal, rendareal,
                  massanominal, massareal)
### Transformar em série temporal
pnadcm = ts(data, start=c(2012,03), freq=12)
colnames(pnadcm) <- c('População', 'PIA', 'PEA', 'PO', "PD",
                      'PNEA', 'Carteira', 'Sem Carteira',
                      'Doméstico','Público', 'Empregador', 
                      'Conta Própria','TFA', 'Agropecuária', 
                      'Indústria', 'Construção', 'Comércio',
                      'Transporte', 'Alojamento', 'Informação', 
                      'Administração Pública','Outros Serviços', 
                      'Serviços Domésticos', 'Renda Nominal', 
                      'Renda Real', 'Massa Nominal', 'Massa Real')



```

# Taxa de Desemprego

```{r, echo=T, eval=T, results='asis', fig.width=8, fig.height=4, fig.align='center', out.width="1\\linewidth", warning=FALSE, message=FALSE, size='small'}

desemprego = pnadcm[,5]/pnadcm[,3]*100
desemprego_sa = final(seas(desemprego))
times = seq(as.Date('2012-03-01'), as.Date('2019-03-01'), 
            by='1 month')

df = data.frame(time=times, desemprego=desemprego,
                desemprego_sa=desemprego_sa)

ggplot(df, aes(x=time))+
  geom_line(aes(y=desemprego, colour='Desemprego'))+
  geom_line(aes(y=desemprego_sa, colour='Desemprego SA'), size=1)+
  scale_colour_manual('', values=c('Desemprego'='#01a2d9',
                      'Desemprego SA'='#014d64'))+
  scale_x_date(breaks=date_breaks('1 year'),
               labels=date_format('%Y'))+
  theme(legend.position = c(.2,.8))+
  xlab('')+ylab('% PEA')+
  labs(title='Desemprego cai lentamente no país')+
  theme_economist()
  


```

# Hiato do Produto

```{r, echo=T, eval=T, results='asis', fig.width=8, fig.height=4, fig.align='center', out.width="1\\linewidth", warning=FALSE, message=FALSE, size='small'}

data = read_excel('ipea.xlsx', range='B2:C106')
colnames(data) = c('pibp','pibe')
time = seq(as.Date('1993-03-01'), as.Date('2018-12-01'), by='3 month')

hiato = (data[,2]/data[,1]-1)*100

df2 = data.frame(time=tail(time,30), hiato=tail(hiato,30))
colnames(df2) = c('time', 'hiato')

ggplot(df2, aes(time, hiato))+
  annotate("rect", fill = "#01a2d9", alpha = 0.3, 
           xmin = as.Date('2014-12-01'), 
           xmax = as.Date('2018-12-01'),
           ymin = -Inf, ymax = Inf)+
  geom_line(size=.8, colour='#014d64')+
  geom_hline(yintercept=0, colour='black', linetype='dashed')+
  scale_x_date(breaks = date_breaks("1 years"),
               labels = date_format("%Y"))+
  labs(title='Hiato do Produto')+
  xlab('')+ylab('%')+
  theme(axis.text.x=element_text(angle=45, hjust=1))+
  theme_economist()


```

# Desemprego vs. Hiato do Produto

```{r, echo=T, eval=T, results='asis', fig.width=8, fig.height=4, fig.align='center', out.width="1\\linewidth", warning=FALSE, message=FALSE, size='small'}

g1 = ggplot(df, aes(x=time))+
  annotate("rect", fill = "#01a2d9", alpha = 0.3, 
           xmin = as.Date('2017-02-01'), 
           xmax = as.Date('2019-03-01'),
           ymin = -Inf, ymax = Inf)+
  geom_line(aes(y=desemprego, colour='Desemprego'))+
  geom_line(aes(y=desemprego_sa, colour='Desemprego SA'), size=1)+
  scale_colour_manual('', values=c('Desemprego'='#01a2d9',
                      'Desemprego SA'='#014d64'))+
  scale_x_date(breaks=date_breaks('1 year'),
               labels=date_format('%Y'))+
  theme(legend.position = c(.2,.8))+
  xlab('')+ylab('% PEA')+
  labs(title='Taxa de Desemprego',
       caption='Fonte: IBGE')+
  theme_economist()

g2 = ggplot(df2, aes(time, hiato))+
  annotate("rect", fill = "#01a2d9", alpha = 0.3, 
           xmin = as.Date('2016-12-01'), 
           xmax = as.Date('2018-12-01'),
           ymin = -Inf, ymax = Inf)+
  geom_line(size=.8, colour='#014d64')+
  geom_hline(yintercept=0, colour='black', linetype='dashed')+
  scale_x_date(breaks = date_breaks("1 years"),
               labels = date_format("%Y"))+
  labs(title='Hiato do Produto',
       caption='Fonte: IPEA')+
  xlab('')+ylab('%')+
  theme(axis.text.x=element_text(angle=45, hjust=1))+
  theme_economist()

grid.arrange(g2, g1, 
             ncol=2)

```
